if NAME="Description" then do;
ROLE="TARGET";
LEVEL="NOMINAL";
ORDER="";
end;
if NAME="InvoiceNo" then do;
ROLE="ID";
LEVEL="INTERVAL";
ORDER="";
end;
if NAME="Quantity" then do;
ROLE="REJECTED";
LEVEL="INTERVAL";
ORDER="";
end;
if NAME="StockCode" then do;
ROLE="REJECTED";
LEVEL="INTERVAL";
ORDER="";
end;
if NAME="VAR1" then do;
ROLE="REJECTED";
LEVEL="INTERVAL";
ORDER="";
end;
drop DROP;
